# SPDX-License-Identifier: MIT
# Copyright (c) 2020 The Authors.

# Authors: Phu Tran          <@phudtran>

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fwds.zeta.com
spec:
  scope: Namespaced
  group: zeta.com
  names:
    kind: Fwd
    plural: fwds
    singular: fwd
    shortNames:
      - fwd
      - fwds
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Status
          type: string
          priority: 0
          jsonPath: .spec.status
        - name: Dft
          type: string
          priority: 0
          jsonPath: .spec.dft
          description: The DFT that this Fwd is using
        - name: Droplet
          type: string
          priority: 0
          jsonPath: .spec.droplet
          description: The droplet where this fwd is deployed
        - name: CreateTime
          type: string
          priority: 0
          jsonPath: .spec.createtime
          description: Time the object is created
        - name: ProvisionDelay
          type: string
          priority: 0
          jsonPath: .spec.provisiondelay
          description: Time to provision an object from creation
